### ISSUE TITLE
No input found for attachment_preview

### ISSUE THREAD

**Issue by kalashnikovisme** [andreapavoni/simple_form_fancy_uploads#15]
Rails 4.2.1
SimpleForm 3.1.0

I have added `gem 'simple_form_fancy_uploads'` , ran `bundle install` and restarted rails server.

`= f.input :file, as: :attachment_preview`

**Comment by yanyingwang** [comment]
I don't know why, but for me, it'll be ok if remove this gem `rails-jquery-autocomplete`.

**Comment by yanyingwang** [comment]
Also, I just follow [simple form custom input doc](http://simple-form.plataformatec.com.br/#custom-inputs) and put [class from code](https://github.com/apeacox/simple_form_fancy_uploads/blob/master/lib/simple_form_fancy_uploads/image_preview_input.rb) to `app/inputs/image_preview_input.rb`.
Everything works perfect, now.

**Comment by g3d** [comment]
@kalashnikovisme @yanyingwang that can be fixed with this lines in simple_form initializer:
```ruby
SimpleForm::FormBuilder.map_type :image_preview, to: SimpleForm::Inputs::ImagePreviewInput
SimpleForm::FormBuilder.map_type :attachment_preview, to: SimpleForm::Inputs::AttachmentPreviewInput
```

Will create PR for that.

**Comment by ngelx** [comment]
+1 
Problems for me started when added 'enum_help' gem.

I can confirm that the solution propose by @g3d works like a charm, I've not tested the PR, but at least manually adding those line to simple_form initializer works.

Thanks @g3d
