### ISSUE TITLE
Update gem in RubySpec

### ISSUE THREAD

**Issue by dayvough** [andreapavoni/simple_form_fancy_uploads#25]
Currently https://rubygems.org/gems/simple_form_fancy_uploads is stuck in the 0.2 release. You have to input the following code to get the 0.5 release.

```ruby
gem 'simple_form_fancy_uploads',  github: 'andreapavoni/simple_form_fancy_uploads', branch: 'master'
```

**Comment by andreapavoni** [comment]
released 0.5.0 on rubygems
